# Default theme for treeviz
# Adaptive colors that work well in both light and dark terminals
name: default
styles:
  # Tree structure elements
  icon:
    light: "#0066CC"
    dark: "#66B3FF"
  label:
    light: "#000000"
    dark: "#FFFFFF"
  extras:
    light: "#495057"
    dark: "#ADB5BD"
  numlines:
    light: "#ADB5BD"
    dark: "#6C757D"
  position:
    light: "#CED4DA"
    dark: "#CED4DA"
  type:
    light: "#6600CC"
    dark: "#B366FF"
  
  # Semantic styles
  default:
    light: "#000000"
    dark: "#FFFFFF"
  muted:
    light: "#ADB5BD"
    dark: "#6C757D"
  subdued:
    light: "#495057"
    dark: "#ADB5BD"
  faint:
    light: "#CED4DA"
    dark: "#CED4DA"
  info:
    light: "#0066CC"
    dark: "#66B3FF"
  emphasis:
    light: "bold #000000"
    dark: "bold #FFFFFF"
  strong:
    light: "bold #000000"
    dark: "bold #FFFFFF"
  warning:
    light: "#CC6600"
    dark: "#FFB366"
  error:
    light: "#CC0000"
    dark: "#FF6666"
  success:
    light: "#009900"
    dark: "#66FF66"