name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  python-unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
          cache-key-prefix: "test-env-v2-${{ matrix.python-version }}"

      - name: Run tests
        run: |
          poetry run pytest -m '' -v --cov-branch --cov-report=xml --cov-report=term --cov=treeviz --junit-xml=test-results.xml python/tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: unit-test-results-python-${{ matrix.python-version }}
          path: |
            test-results.xml
            coverage.xml
          retention-days: 30

      - name: Upload test report
        uses: dorny/test-reporter@v1
        if: success()
        with:
          name: Unit Tests Report (Python ${{ matrix.python-version }})
          path: "test-results.xml"
          reporter: java-junit
          fail-on-error: false

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
